import type { NextPage, NextPageContext } from "next";
import { getSession, useSession } from "next-auth/react";
import Head from "next/head";

import { Box } from "@chakra-ui/react";

import { Auth, Chat } from "@/components";

const Home: NextPage = () => {
  const { data: session } = useSession();

  const userExists = !!session?.user?.username;

  const reloadSession = () => {};

  return (
    <>
      <Head>
        <title>iChat | Home</title>

        <meta name="description" content="Generated by create next app" />

        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box>
        {userExists ? (
          <Chat />
        ) : (
          <Auth session={session} onReloadSession={reloadSession} />
        )}
      </Box>
    </>
  );
};

export const getServerSideProps = async (ctx: NextPageContext) => {
  const session = await getSession(ctx);

  return {
    props: {
      session,
    },
  };
};

export default Home;
